#tabuada
n= int(input("digite um número:"))
print("===============")
x1= (n*1)
print("{}x1={}".format(n,x1))
x2= (n*2)
print("{}x2={}".format(n,x2))
x3= (n*3)
print("{}x3={}".format(n,x3))
x4= (n*4)
print("{}x4={}".format(n,x4))
x5= (n*5)
print("{}x5={}".format(n,x5))
x6= (n*6)
print("{}x6={}".format(n,x6))
x7= (n*7)
print("{}x7={}".format(n,x7))
x8= (n*8)
print("{}x8={}".format(n,x8))
x9= (n*9)
print("{}x9={}".format(n,x9))
x10= (n*10)
print("{}x10={}".format(n,x10))
print("===============")
